### ISSUE TITLE
Ad-Ops: spreadsheet tool/method to group day-data into week-data

### ISSUE THREAD

**Issue by svevang** [PRX/meta.prx.org#103]
Create a tool that consumes the day oriented data (forecasts, etc) and allows the ad-ops to to incorporate that data into their current workflow.

**Comment by svevang** [comment]
Recording some notes here for posterity. I'm really digging these spreadsheets!!

The Monday Week Sequence
--------------------------

Spreadsheets have built-in week functions based on Sun-Sat. Becase we need values for weeks starting on *Monday* (per broadcast industry practices), we need a way to translate. Here's an sheets expression that does that, it offsets the `WEEKNUM` function for our 'monday' use-case:

```
=if(MOD(WEEKDAY(A2) + 5, 7) = 6, WEEKNUM(A2)-1, WEEKNUM(A2))
```

First, this takes the weekday and shifts it. For example if `A2` is a Monday, then `MOD(WEEKDAY(A2) + 5, 7` will be 0, Tuesday is 1, Wednesday is 2.  etc. Next, the `IF` statement tests if the date is a Sunday and then shifts it into the previous week index.

Which produces a sequence like:

<img width="746" alt="Screen Shot 2019-05-15 at 11 05 22 AM" src="https://user-images.githubusercontent.com/329012/57790985-7d28a880-7701-11e9-886c-3efe744706e4.png">

Pivot Table Week Sums
------------------------

We can create a pivot table in the usual way and, using these newly generated week sequence values, group and sum by monday_week and podcast id.  Here's a screenshot that illustrates a new pivot table set up this way:

<img width="894" alt="Screen Shot 2019-05-15 at 11 13 42 AM" src="https://user-images.githubusercontent.com/329012/57791590-b4e42000-7702-11e9-95c2-a4981792d800.png">

Note the two "rows" groupings added are monday_week and podcast_id.  The output "values" added are the sums on total_downloads and the mins of the date in that week.   The min function is used to fill in the date of that Monday which begins the week.

**Comment by kookster** [comment]
Is this done @svevang ?

**Comment by svevang** [comment]
Not quite, I can close this after the meeting with ad-ops.
