### ISSUE TITLE
Learn Pager Duty Best Practices

### ISSUE THREAD

**Issue by IcusFMagni** [PRX/meta.prx.org#115]
Pager Duty
https://response.pagerduty.com/

New Relic
https://blog.newrelic.com/engineering/on-call-and-incident-response-new-relic-best-practices/

**Comment by brandonhundt** [comment]
Noting we don't want to overlook the equipment necessary to being on call, such as a MiFi dongle and unlimited data plans:

> Have your laptop and Internet with you (office, home, a MiFi dongle, a phone with a tethering plan, etc).
Have a way to charge your MiFi.

https://response.pagerduty.com/oncall/being_oncall/
