### ISSUE TITLE
Show 100 items in flight and campaign dashboards

### ISSUE THREAD

**Issue by brandonhundt** [PRX/meta.prx.org#132]
Kali has requested we show 100 items by default in the flight and campaign dashboards.https://prx.slack.com/archives/C0B4PQQ8H/p1612981984046900

She acknowledges this may slow the initial page load, but is okay with that.

**Comment by cavis** [comment]
Did you mean to open this in meta?  Probably just a Grove change.

**Comment by brandonhundt** [comment]
Issue moved to [PRX/grove.prx.org #311](https://github.com/PRX/grove.prx.org/issues/311) via [**ZenHub**](https://www.zenhub.com/)
