### ISSUE TITLE
Metrics

### ISSUE THREAD

**Issue by kookster** [PRX/meta.prx.org#14]

**Comment by pkarman** [comment]
@kookster @sandikbarr - are these issues still valid? Should they be added to the general Icebox or Backlog and removed from this Epic?

**Comment by sandikbarr** [comment]
The long answer with backstory- The chart.prx.org repo is not currently being used or kept up to date. It was once a set of separate components that were included in the styleguide, but building component libraries in Angular 2/4 is complex and painful. Those components now live in the styleguide. That's the backstory. 

short answer- PRX/chart.prx.org#14 chart annotations, PRX/chart.prx.org#15 chart sharing, and PRX/chart.prx.org#16 ad charting should remain ice boxed. PRX/chart.prx.org#17 geography should be closed and handled in more specific tickets. PRX/chart.prx.org#13
chart date range selection should be closed as Done, and PRX/chart.prx.org#18 should be ice boxed.

more long answer- whether we should ice box in chart.prx.org or styleguide.prx.org or move some of these to the front or back end application repos, metrics.prx.org or castle.prx.org is another question. PRX/chart.prx.org#14 chart annotations is at the chart component level, so either chart.prx.org or styleguide.prx.org. PRX/chart.prx.org#15 chart sharing is front end application stuff, so metrics.prx.org is where that one should go. PRX/chart.prx.org#16 ad charting is a playback metrics thing and belongs in both metrics and castle and probably the embeddable player. PRX/chart.prx.org#18 iTunes metrics is both front and backend, so castle and metrics.

**Comment by pkarman** [comment]
thanks for the details @sandikbarr 

IMO the particular repo the issue lives in is less important than that it gets groomed and processed. Since we see all issues via zenhub as across the org, there's limited benefits in "correctly" assigning the ticket to a particular repo. I'd be in favor of leaving these all in the `chart` repo unless that somehow impacts the visibility we have vis-a-vis grooming, in some way I'm not seeing.

**Comment by sandikbarr** [comment]
Leaving them in chart.prx/org works for me, @pkarman. What to do about that component library Angular build is a bit up in the air, so it's not going anywhere.
