### ISSUE TITLE
set priority label on 10 tickets

### ISSUE THREAD

**Issue by pkarman** [PRX/meta.prx.org#44]
In order to start the process of digging out our backlog, each team member is asked to assign priority to 10 tickets during the course of the Sprint. The 10 tickets need not necessarily be tickets you created, but you should have some reasonable sense of the priority (low, medium, high) of each. The tickets may come from the `Backlog` or `New` swimlanes.

Check off your name when you've finished your 10. Note that this is the *initial* priority and may change as the result of more grooming.

* [x] @kookster 
* [x] @gcampo88 
* [x] @cavis 
* [x] @sandikbarr 
* [x] @farski 
* [x] @debenedictis 
* [ ] @palomao

**Comment by debenedictis** [comment]
I updated three tickets I had opened (in 2015) where I had "some reasonable sense of the priority."
