### ISSUE TITLE
Make sure PRs are getting built

### ISSUE THREAD

**Issue by cavis** [PRX/meta.prx.org#56]
Not confident that PRs here are getting CodeBuild'd correctly.  Get confident.

Need to run these PRs so we can have some confidence that a merged PR will pass.

**Comment by farski** [comment]
@cavis This is talking specifically about PR's to meta for the acceptance test suite, right?

**Comment by cavis** [comment]
Yep.  Just to give a bit more assurance that PRs here "work" before merging.

**Comment by cavis** [comment]
This is done!
