### ISSUE TITLE
Intermittent js test failures

### ISSUE THREAD

**Issue by cavis** [PRX/meta.prx.org#66]
Just capturing places the tests tend to fail.

**Comment by cavis** [comment]
- [2018/01/09 00:18:21](https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logEventViewer:group=/aws/codebuild/infrastructure-cd-AcceptanceTests;stream=203fa8f5-b5ed-406b-8675-608e719c6662)
  - test_0001_creates new episode with RSS feed ERROR (113.31s)
  - test_0001_registers when podcast is played ERROR (120.39s)

**Comment by pkarman** [comment]
@cavis I don't have access to AWS - any chance you could copy/paste the actual error logs here? or is what you've got already here the only thing in the logs?

**Comment by cavis** [comment]
- [2018/01/10 17:50:24](https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logEventViewer:group=/aws/codebuild/infrastructure-cd-AcceptanceTests;stream=85c36390-7d94-49de-a38f-aea4e10a0769)
  ```
  publish::js::audio
    test_0001_creates new episode with RSS feed ERROR (129.03s)
      NoMethodError: NoMethodError: undefined method `attribute' for nil:NilClass
      /usr/local/bundle/gems/nokogiri-1.8.1/lib/nokogiri/xml/node_set.rb:167:in `attr'
      /codebuild/output/src491727864/src/test/support/publish_dsl.rb:243:in `publish_fetch_rss_media_url'
      /codebuild/output/src491727864/src/test/publish/basic_test.rb:31:in `block (3 levels) in <top (required)>'
  ```

**Comment by cavis** [comment]
@pkarman updated with stack traces inline.

**Comment by cavis** [comment]
Here's a different one:

- [2018/01/11 17:12:25](https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logEvent:group=/aws/codebuild/infrastructure-cd-AcceptanceTests;stream=b8443000-05cc-43c8-afeb-5ce5922d7baf)
  ```
  metrics::js::basic
    test_0001_registers when podcast is played FAIL (64.03s)
      Minitest::Assertion: expected to find text "Test Episode f9314fe4fce51bf434cb" in "PRX Test Series f9314fe4fce51bf434cb test test Please wait... Dec 31 Jan 2 Jan 4 Jan 6 Jan 8 Jan 10 Episode All Episodes Release Date Total for Period Dec 31 Jan 1 Jan 2 Jan 3 Jan 4 Jan 5 Jan 6 Jan 7 Jan 8 Jan 9 Jan 10 Jan 11 0 0 0 0 0 0 0 0 0 0 0 0 0 < 1 > You're seeing a beta preview of prx.org. Let us know what you think. Use Old Version Company About Us Blog Team Press Funding Donate Support Help Status Terms Privacy Projects Radiotopia Matter Ventures".
      /usr/local/bundle/gems/capybara_minitest_spec-1.0.6/lib/capybara_minitest_spec.rb:42:in `block in define_assertion'
      /codebuild/output/src206953507/src/test/metrics/basic_test.rb:17:in `block (3 levels) in <top (required)>'
  ```

**Comment by sandikbarr** [comment]
This seems like a new one, but still looks like a timing issue.

```
dovetail-programs::criminal
test_0001_matches the production mp3 FAIL (0.00s)
Minitest::Assertion: Expected: 200
Actual: 404
/codebuild/output/src890411166/src/test/dovetail/programs_test.rb:58:in `block (4 levels) in <top (required)>'

**Comment by cavis** [comment]
Yeah, I'm kind of confused by that dovetail one - was unable to duplicate locally.  Could have been a few different issues - opened a new ticket #73 to cover those.

**Comment by pkarman** [comment]
Since we have disabled/trimmed the expensive JS tests, let's close this particular catch-all ticket now and open failure-specific ones like #73
